name: Build and Push Docker Image

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract and format repository name
        run: |
          CLEAN_REPO=$(echo "${GITHUB_REPOSITORY}" | sed -E 's/.*[:\/]([^\/]+\/[^\/]+)$/\1/' | sed 's/\.git$//' | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=${CLEAN_REPO}" >> $GITHUB_ENV

      # Genera metadata y tags automáticos (latest + SHA corto)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO_LOWER }}
          tags: |
            type=sha,format=short
            type=raw,value=latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}